---
- name: Add PostgreSql repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    filename: pgdg

- name: Add repository PostgreSql key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: install Postgres
  apt:
    name:
      - "postgresql-{{ postgres_version }}"
      - "postgresql-client-{{ postgres_version }}"
#    ignore_errors: "{{ ansible_check_mode }}"

#- name: Copy PostgreSql config
#  template:
#    src: postgresql.conf.j2
#    dest: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
#    owner: postgres
#    mode: 0644