---
- name: Enable nginx service
  hosts: webserver
  remote_user: root
  tasks:
    - name: Install nginx
      apt:
        name: nginx-extras
        update_cache: yes
    - name: Start nginx
      systemd:
        name: nginx
        enabled: yes
        state: started
    - name: Add index.html
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        mode: 0664
    - name: Update nginx config
      copy:
        src: files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0664
      notify: Reload nginx
  handlers:
    - name: Reload nginx
      systemd:
        name: nginx
        daemon_reload: true
        state: reloaded
